server:
  port: 9192

#spring:
#  kafka:
#    consumer:
#      bootstrap-server: localhost:2181
#      group-id: consumer-group-1
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.mdk.app.dto