spring:
  application:
    name: card-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    preferIpAddress: true